config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  root 'users#index'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end

  # API endpoints
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all # everybody have the read access to everything

    # if the user is authenticated then return the ability object instead of returning an error
    return unless user.present?

    can :manage, Post, author_id: user.id
    can :manage, [Comment, Like], user_id: user.id

    # if the user is admin then return the ability object instead of returning an error
    return unless user.role == 'admin'

    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :user_id
  belongs_to :post

  validates :text, presence: true

  after_create :comments_counter
  after_destroy :comments_counter

  def comments_counter
    post.update_column(:comments_counter, post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :user_id
  belongs_to :post

  after_create :likes_counter
  after_destroy :likes_counter

  def likes_counter
    post.update_column(:likes_counter, post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :comments, foreign_key: :post_id, dependent: :destroy
  has_many :likes, foreign_key: :post_id, dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :text, presence: true
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0 }

  after_create :user_posts_count
  after_destroy :user_posts_count

  def user_posts_count
    author.update_column(:posts_counter, author.posts.count)
  end

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments, foreign_key: :user_id
  has_many :likes, foreign_key: :user_id
  has_many :posts, foreign_key: :author_id

  validates :name, presence: true
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0 }

  def recent_post_by_author(author_id)
    posts.where(author_id:).order(created_at: :desc).limit(3)
  end

  def set_default_user_role
    self.role ||= 'admin'
  end
end

app/controllers/api/V1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create]

  def index
    user = User.find(params[:user_id])
    post = user.posts.find(params[:post_id])
    comments = post.comments
    render json: comments
  rescue ActiveRecord::RecordNotFound
    render json: { error: 'Comment not found' }, status: 404
  end

  def create
    @post = Post.find(params[:post_id])
    json_request = JSON.parse(request.body.read)
    text = json_request['text']
    author = @post.author

    @comment = @post.comments.new(text:, author:)
    if @comment.save
      render json: @comment, status: :created
    else
      render json: { error: 'Invalid comment' }, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/V1/posts_controller.rb
class Api::V1::PostsController < ActionController::API
  # GET users/user_id/posts this endpoint will return all posts for a given user
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts

    render json: @posts
  rescue ActiveRecord::RecordNotFound
    render json: { error: 'User not found' }, status: :not_found
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name role])
  end

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:name, :email, :password, :password_confirmation, :role)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]
  before_action :find_post_by_id, only: %i[new create destroy]

  def new
    @user = current_user
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @user = current_user
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(post: @post, author: @user, text: comment_params[:text])
    if @comment.save
      flash[:notice] = 'Comment successfully added!'
      redirect_to user_post_path(@user, @post)
    else
      flash[:alert] = 'Comment could not be added.'
      redirect_to new_user_post_comment_path(@user, @post)
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    authorize! :destroy, comment
    if comment.destroy
      flash[:notice] = 'The Post was deleted successfully!'
    else
      flash[:error] = 'Error! The Post was not deleted'
    end
    redirect_to user_post_path(@post.author, @post)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end

  def find_post_by_id
    @post = Post.find(params[:post_id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = 'Error! Post not found'
    redirect_to user_posts_path
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = Like.new(post: @post, author: current_user)

    if @like.save
      flash[:notice] = 'You have liked the post!.'
    else
      flash[:alert] = "Something is wrong!, you don't liked the post!."
    end

    redirect_to user_post_path(current_user.id, @post.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create addlike deletelike destroy]
  before_action :find_user_by_id, only: %i[index show]

  def index
    @posts = @user.posts.page(params[:page]).per(3).order('created_at ASC')
  end

  def show
    @post = Post.includes(comments: :author).find(params[:id])
  end

  def new
    @user = current_user
    @new_post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:notice] = 'Post successfully added!'
      redirect_to user_path(current_user)
    else
      flash[:alert] = 'Post could not be added.'
      redirect_to new_user_post_path(current_user)
    end
  end

  def destroy
    @post = Post.includes(comments: :author).find(params[:id])
    authorize! :destroy, @post
    if @post.destroy
      flash[:notice] = 'Post successfully deleted!'
    else
      flash[:alert] = 'Post could not be deleted.'
    end
    redirect_to user_path(current_user)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end

  def find_user_by_id
    @user = User.find(params[:user_id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = 'Error! User not found'
    redirect_to users_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user_by_id, only: [:show]

  def index
    @users = User.all
  end

  def show; end

  def find_user_by_id
    @user = User.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = 'Error! User not found'
    redirect_to users_url
  end
end

app/helpers/api/comments_helper.rb
module Api::CommentsHelper
end

app/helpers/api/posts_helper.rb
module Api::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<section class="container flex-col">
  <h1 class="text-4xl text-center mb-4">
    Add a new Comment for <%= @post.author.name %>'s post #<%= @post.id %>
  </h1>

  <% if flash[:alert].present? %>
  <div
    class="alert notice italic font-bold text-xl text-red-500 text-center py-2"
  >
    <%= flash[:alert] %>
  </div>
  <% end %> <%= form_with model: [@user, @post, @comment], url:
  user_post_comments_path(@user, @post), class: 'p-4 border border-gray-300' do
  |form| %>
  <div class="mb-4">
    <%= form.label :Comment, class: 'block text-gray-700 font-bold mb-2' %> <%=
    form.text_area :text, class: 'w-full p-2 border rounded-md
    focus:outline-none focus:ring focus:border-blue-300' %>
  </div>
  <div class="mb-4">
    <%= form.submit 'Create Comment', class: 'w-full p-2 bg-blue-500 text-white
    hover:bg-blue-700 rounded-md cursor-pointer' %>
    <% end %>
  </div>
  
  <%= render 'layouts/root'%>
</section>

app/views/layouts/_root.html.erb
<div class="text-3xl hover:scale-y-125 transition-all">
  <%= link_to root_path do%>
    <button type="button">Back to Main page</button>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Blog App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      </div> 
        <% if user_signed_in? %>
        <span class="flex justify-between px-8">
          <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete } %>
          <p>Name : <strong><%= current_user.name %></strong> role:<strong> <%= current_user.role %> </strong></p>
          </span>
        <% else %>
        <div class="text-right text-xl flex justify-between">
          <span class="p-4">
            <%= link_to 'Sign In', new_user_session_path %>
          </span>
          <span class="p-4">
            <%= link_to 'Sign Up', new_user_registration_path %>
          </span>
        </div>
        <% end %>
      </div>
      <div>
        <p class="notice italic font-bold text-xl text-red-500 text-center py-2"><%= notice %></p>
        <p class="alert italic font-bold text-xl text-red-500 text-center py-2"><%= alert %></p>
      </div>
    </header>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/index.html.erb
<section class="container flex-col pb-8">
<h1 class="text-center text-5xl">List of Posts by User</h1>

  <header class="pl-3 pr-3 border-solid border-1 bg-gray-300 grid grid-cols-4 relative">
    <div class="col-span-1">
      <% if @user.photo.present? %>
        <%= image_tag @user.photo %>
      <% else %>
        <p>::::: No photo ::::: 📸</p>
      <% end %>
    </div>
    <h2 class="text-4xl my-auto font-bold col-span-2"><%= @user.name %></h2>
    <p class="col-span-1 absolute right-4 bottom-2">Number of posts: <%= @user.posts_counter %></p>    
  </header>

  <div class="pb-4">
    
        <ul>
          <% @posts.each do |post| %>
          <li>
            <div class="bg-gray-200 relative p-4 ">
              <%= link_to user_post_path(id: post.id) do%>
                <h3 class="text-2xl hover:scale-y-125 transition-all hover:bg-gray-300">
                  Post #<%= post.id %>, Title: <strong><%= post.title.capitalize %></strong>
                </h3>
              <% end %>
              <p class="py-8"><%= post.text %></p>
              <p class="text-right">
                Comments: <%= post.comments_counter%>, Likes: <%=
                post.likes_counter%>
              </p>
            </div>  

            <ul class="bg-gray-200 border-t border-gray-300">
              <% post.recent_comments.each do |comment| %> <% if post.id ==
              comment.post_id %>
              <li>
                <div class="pl-4 py-1">
                  <strong><%=comment.author.name%>:</strong>
                  <i><%= comment.text %></i>
                  <% if can?(:destroy, comment) %>
                    <%= button_to 'Delete comment', user_post_comment_path(comment.post.author, comment.post, comment), method: :delete,
                      class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' %>
                    <% end %>
                </div>
              </li>
              <% end %> <% end %>
            </ul>
          </li>
          <% end %>
        </ul>      
    
  </div>

  <div class="pagination text-3xl my-4 text-right">
  <%= paginate @posts %>
</div> 
  <%= render 'layouts/root'%>
</section>

app/views/posts/new.html.erb
<section class="container flex-col">
  <h1 class="text-4xl text-center">
    Add a new Post for current user (<%= @user.name %>)
  </h1>
  <div>
    <% if flash[:alert].present? %>
    <div class="alert italic font-bold text-xl text-red-500 text-center py-2">
      <%= flash[:alert] %>
    </div>
    <% end %>
  </div>
  <div class="p-4">
    <%= form_with model: [@user, @new_post] do |form| %>
      <div class="w-full mb-4">
        <%= form.label :Title %> <%= form.text_field :title, class: 'w-full p-2 border border-gray-300' %>
      </div>
      <div class="w-full mb-4">
        <%= form.label :Description %> <%= form.text_area :text, class: 'w-full p-2 border border-gray-300' %>
      </div>
      <div class="w-full">
        <%= form.submit 'Create Post', class: 'w-full p-2 bg-blue-500 text-white hover:bg-blue-700' %>
      </div>
    <% end %>
  </div> 
  <%= render 'layouts/root'%>
</section>

app/views/posts/show.html.erb
<section class="container flex-col">
  <header class="pl-3 pr-3 border-solid border-1 bg-gray-300 grid grid-cols-4 relative">
    <div class="col-span-1">
      <% if @user.photo.present? %>
        <%= image_tag @user.photo %>
      <% else %>
        <p>::::: No photo :::::</p>
      <% end %>
    </div>
    <h1 class="text-5xl my-auto font-bold col-span-2">Post #
      <%=@post.id%> by <%= @post.author.name%>
    </h1>
    <p class="col-span-1 absolute right-2 bottom-2">
      Comments: <%= @post.comments_counter%>, Likes: <%= @post.likes_counter%>
    </p>
  </header>

  <div class="bg-gray-200 relative p-4">
    <h2 class="text-2xl pb-4 font-bold"><%=@post.title%></h2>
    <p class="text-2xl"><%=@post.text%></p>
    <div class="w-12 right-0 top-2 absolute hover:scale-y-125 transition-all">
      <%= form_tag user_post_likes_path(@post.author, @post), method: :post do %>
        <%= hidden_field_tag :id, @post.id %>
        <%= image_tag 'heart.png', alt: 'Like', class: 'cursor-pointer', onclick: 'this.closest("form").submit();' %>
      <% end %>
    </div>
    <div>
      <% if can?(:destroy, @post) %>
        <%= button_to 'Delete Post', user_post_path(@post.author, @post), method: :delete,
            class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' %>
        <% end %>
    </div>
  </div>

  <ul class="p-4 border-t border-b border-gray-300 bg-gray-200">
    <% @post.comments.reverse.each do |comment| %>
      <li class="text-xl">
        <strong><%=comment.author.name%>:</strong> <i><%= comment.text %></i>
      </li>
    <% end %>
  </ul>
  
  <div class="flex justify-between gap-8 pt-4 pb-10">
    <div class="text-3xl hover:scale-y-125 transition-all">
      <%= link_to new_user_post_comment_path(post_id: @post.id) do %>
      <h2>Add new Comment</h2>
      <% end %>
    </div>
    <%= render 'layouts/root'%>
  </div>
</section>

app/views/users/index.html.erb
  <section class="container flex flex-col gap-4">
    <h1 class='text-3xl md:text-5xl text-center font-bold pb-4'>List of Users</h1>

    <% if @users.present? %> 
      <ul class="bg-gray-200">
        <% @users.each do |user| %>
          <li class="pb-4 hover:bg-gray-300 relative">
            <div class="flex gap-4">

              <div>
                <% if user.photo.present? %>
                  <img src="<%= user.photo %>" alt="photo" class="rounded" width="100px">
                <% else %>
                <p>::::: No photo ::::: 📸</p>
                <% end %>
              </div>

              <div class="flex gap-2">
                <%= link_to user_path(id: user.id) do %>        
                  <h2 class="text-2xl font-bold hover:scale-y-125 transition-all">
                    <%= user.name %>
                  </h2>              
                <% end %>              
              </div>  

              <div class="flex">
                <p class="text-sm bottom-2 right-2 absolute ">Number of posts: <%= user.posts_counter %></p>        
              </div>
            </div>
          </li>
        <% end %> 
      </ul>
    <% else %>
    
    <p class="text-center text-2xl">No users created.</p>
  <% end %>   
    <% if current_user.present? %>    
    <%= link_to new_user_post_path(current_user) do %>
      <h2 class="pt-5 text-5xl hover:scale-y-125 transition-all">Add a new Post</h2>
    <% end %>
  
<% else %>
  <p class="text-center text-2xl">Sing Up !!!</p>
<% end %>

</section>

app/views/users/show.html.erb
<section class="container flex-col">
  <header
    class="pl-3 pr-3 border-solid border-1 bg-gray-300 grid grid-cols-4 relative"
  >
    <div class="col-span-1">
      <% if @user.photo.present? %>
        <%= image_tag @user.photo %>
      <% else %>
        <p>::::: No photo ::::: 📸</p>
      <% end %>
    </div>
    <h1 class="text-4xl my-auto font-bold col-span-2"><%= @user.name%></h1>
    <p class="col-span-1 absolute right-2 bottom-2">
      Number of posts: <%= @user.posts_counter%>
    </p>
  </header>

  <div class="bg-gray-200 p-4">
    <h3 class="text-2xl">Bio</h3>
    <p class="text-xl"><%= @user.bio%></p>
  </div>

  <div class="bg-gray-200">

    <ul class="p-4">    
      <% @user.recent_post_by_author(@user.id).each do |post| %>
      <li>
        <%= link_to user_post_path(user_id: post.author_id, id: post.id) do%>
        <h3
          class="text-xl font-bold hover:scale-y-125 hover:bg-gray-300 transition-all"
        >
          Post #<%= post.id %>
        </h3>
        <% end %>
        <p class="italic border-t border-gray-300 p-4"><%= post.text%></p>
      </li>
      <% end %>
    </ul>
    
  </div>

  <div class="flex justify-between gap-8 pt-4 pb-10">
    <div>
      <%= link_to user_posts_path(@user) do%>
      <button class="text-3xl hover:scale-y-125 transition-all" type="button">
        User's posts
      </button>
      <% end %>
    </div>  

    <%= render 'layouts/root'%>    
  </div>
</section>